# Generated by Django 4.2.7 on 2026-02-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_sender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
